e_store/e_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_store/website/urls.py
from django.urls import path

from .views import home, register, log_in, admin, customer_home, products_list, product_detail, add_item, update, remove_item, full_remove, cart_detail, place_order, delete, order_page, orders_by_product, log_out


app_name = 'website'

urlpatterns = [
    path('', home, name='home'),
    path('register/', register, name='register'),
    path('log-in/', log_in, name='log_in'),
    path('admin-page/', admin, name='admin'),
    path('customer-home/', customer_home, name='customer_home'),
    path('all-products/', products_list, name='products_list'),
    path('product-detail/<int:product_id>/', product_detail, name='product_detail'),
    path('add-item/<int:product_id>/', add_item, name='add_item'),
    path('update-product/<int:product_id>/', update, name='update'),
    path('order-page/', order_page, name='order_page'),
    path('orders-by-product/<int:product_id>/', orders_by_product, name='orders_by_product'),
    path('remove-item/<int:product_id>/', remove_item, name='remove_item'),
    path('full-remove/<int:product_id>/', full_remove, name='full_remove'),
    path('cart-detail/', cart_detail, name='cart_detail'),
    path('place-order/<str:total>/', place_order, name='place_order'),

    path('delete/<int:product_id>/', delete, name='delete'),
    path('log-out/', log_out, name='log_out'),
]

e_store/templates/admin_page.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Admin {% endblock %}


{% block body %}

<h1>Admin Page</h1>

<div class="container-fluid">
    <a class="btn btn-primary" href="{% url 'website:order_page' %}">Orders</a>

    <div class="container">
        {% for message in messages %}
        <div class="messages" style="font-size: 1.5rem;">
            {{ message }}
        </div>
        {% endfor %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="btn btn-primary" type="submit">Upload</button>

        </form>
    </div>

    <div class="container">
        <h2>All Products</h2>

        <div class="row text-center mx-auto">
            {% for product in products %}
            <div class="text-center col-md-4 mx-auto">
                <a href="{% url 'website:orders_by_product' product.id %}">
                    <div class="product card shadow" style="width: 10rem;">
                        <div>
                            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.image }}">
                        </div>
                        <h4>{{ product.name }}</h4>
                        PRICE: {{ product.price }}<br>
                        STOCK: {{ product.stock }}
                        <div>
                            <a class="btn btn-warning" href="{% url 'website:update' product.id %}">Edit</a>
                            <a class="btn btn-danger" href="{% url 'website:delete' product.id %}">Delete</a>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}

        </div>
    </div>

</div>

{% endblock %}

e_store/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/b040b70f9a.js" crossorigin="anonymous"></script>

    <link href=" {% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href=" {% static 'css/styles.css' %}" rel="stylesheet">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    
{% include 'header.html' %}

{% block body %}
{% endblock %}


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

e_store/templates/cart.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} User | {{ user.username }} {% endblock %}


{% block body %}

{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center">
            Cart is Empty.
        </h1>
        <br>
        {% for message in messages %}
        <div class="messages" style="font-size: 1.5rem; color:green">
            {{ message }}
        </div>
        {% endfor %}
        <p class="text-center">
            <a href="{% url 'website:products_list' %}">Continue Shopping</a>
        </p>
    </div>

</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center">
            Your Cart
        </h1>
        <br>
        {% for message in messages %}
        <div class="messages" style="font-size: 1.5rem; color:green">
            {{ message }}
        </div>
        {% endfor %}
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-7 text-center">
        <table class="table">
            <thead class="table-success">
                <tr>
                    <th colspan="5">Your Items</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                <tr>
                    <td>
                        <!-- <a href="item.product.get_absolute_url"> -->
                        <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}"
                            style="width: 100px; height: 200px;">
                        </a>
                    </td>
                    <td class="text-left">
                        <h2>{{ item.product.name }}</h2>
                        <br>
                        Price: ₹{{ item.product.price }}
                        <br>
                        Qty : {{ item.quantity }} x {{ item.product.name }}
                    </td>
                    <td>
                        {{ item.sub_total }}
                    </td>
                    {% if item.quantity < item.product.stock %} <td><a
                            href="{% url 'website:add_item' item.product.id %}"><i class="fa-solid fa-plus"></i></a>
                        &nbsp;<a href="{% url 'website:remove_item' item.product.id %}"><i
                                class="fa-solid fa-minus"></i></a>
                        &nbsp;<a href="{% url 'website:full_remove' item.product.id %}"><i
                                class="fa-solid fa-trash"></i></a>
                        </td>
                        {% else %}
                        <td>
                            <a href="{% url 'website:remove_item' item.product.id %}"><i
                                    class="fa-solid fa-minus"></i></a>
                            &nbsp;<a href="{% url 'website:full_remove' item.product.id %}"><i
                                    class="fa-solid fa-trash"></i></a>
                        </td>
                        {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-5 text-center">
        <table class="table">
            <thead class="table-success">
                <tr>
                    <th>Checkout</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Please review your cart items before proceeding with the order payment.
                    </td>
                </tr>
                <tr>
                    <td><strong>Your Total : {{ total }}</strong></td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'website:place_order' total %}" class="btn btn-success">Place Order</a>
            <a href="{% url 'website:products_list' %}" class="btn btn-primary">Continue Shopping</a>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

e_store/templates/customer_home.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} User | {{ user.username }} {% endblock %}


{% block body %}

<h1>User | {{ user.username }}</h1>
<hr>

<a class="btn btn-primary" href="{% url 'website:products_list' %}">All Products</a>

{% endblock %}

e_store/templates/delete.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Delete | {{ product.name }} {% endblock %}


{% block body %}

<div class="container shadow" style="width: 30%;">
    <form action="" method="post">
        {% csrf_token %}

        <p><b>Are you sure you want to delete <span style="color:darkgreen; font-size: 30px;">{{ product.name }}</span> ?</b></p>
        <div>
        <button class="btn btn-danger" type="submit">Delete</button>
        <a class="btn btn-success" href="{% url 'website:admin' %}">Cancel</a>
    </form>

</div>

{% endblock %}

e_store/templates/header.html
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
    <div class="container-fluid">
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'website:home' %}">E-Store | {{ user.username }}</a>

        {% else %}
        <a class="navbar-brand" href="{% url 'website:home' %}">E-Store</a>
        {% endif %}

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'website:home' %}">Home</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'website:cart_detail' %}">
                        Cart
                    </a>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'website:log_out' %}">LogOut</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'website:log_in' %}">LogIn</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'website:register' %}">Register</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

e_store/templates/index.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} E-Store {% endblock %}


{% block body %}

<div class="container-fluid home-card">

    <div class="row">

        <div class="shadow col-md-12">
            <div class="card-body">
                <h1>WELCOME</h1>
                {% if user.is_authenticated %}
                <div>
                    {% for message in messages %}
                    <div class="messages">
                        <h4 style="color: red; font-size: 1.5rem;">{{ message }}</h4>
                    </div>
                    {% endfor %}
                    <div>
                        <a href="{% url 'website:home' %}">Return to User Home</a>
                    </div>
                </div>
                {% else %}
                <div>
                    <a href="{% url 'website:register' %}" class="btn btn-outline-primary">Register</a>
                    <a href="{% url 'website:log_in' %}" class="btn btn-outline-success">LogIn</a>
                </div>
                {% endif %}
            </div>
        </div>

    </div>

</div>

{% endblock %}

e_store/templates/login.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Login {% endblock %}


{% block body %}

<div class="login-form">

    <form action="" method="POST">
        <h2>LOG IN</h2>

        {% for message in messages %}
        <div class="messages" style="font-size: 1.5rem;">
            {{ message }}
        </div>
        {% endfor %}

        {% csrf_token %}

        {{ form }}

        <br>
        <div class="d-grid">
            <button class="btn btn-primary" type="submit">SignIn</button>
        </div>
    </form>

</div>

{% endblock %}

e_store/templates/order_page.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Orders {% endblock %}


{% block body %}

<h1>Orders</h1>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Order ID</th>
                <th scope="col">User</th>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Date</th>
            </tr>
        </thead>
        {% for order in orders %}
        <tbody>
            <tr>
                <th scope="row">{{ order.id }}</th>
                <td>{{ order.cart.user.username }}</td>
                <td>{{ order.cart.product.name }}</td>
                <td>{{ order.cart.quantity }}</td>
                <td>{{ order.date }}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    <a href="{% url 'website:admin' %}">Return to Admin Page</a>
</div>

{% endblock %}

e_store/templates/product_order.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Orders {% endblock %}


{% block body %}

<h1>Orders</h1>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Order ID</th>
                <th scope="col">User</th>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Date</th>
            </tr>
        </thead>
        {% for key, order in orders.items %}
        <tbody>
            <tr>
                <th scope="row">{{ key }}</th>
                <td>{{ order.User }}</td>
                <td>{{ order.Product }}</td>
                <td>{{ order.Quantity }}</td>
                <td>{{ order.Date }}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    <a href="{% url 'website:admin' %}">Return to Admin Page</a>
</div>

{% endblock %}

e_store/templates/product_page.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Product | {{ product.name }} {% endblock %}


{% block body %}

<div class="product-page container">
    <div class="row">
        <h1 style="text-transform: uppercase;">{{ product.name }}</h1>
        <p>₹{{ product.price }}</p>
        <hr>
        <div class="card shadow col-md-4">
            <div>
                <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
            </div>
        </div>
        <div class="col-md-8">
            <div class="product-description">

                <h4>Product Description</h4>
                <p>{{ product.description }}</p>
                

                {% if product.stock <= 0 %} <p><b>Out of Stock</b></p>
                {% else %}  

                    <div>
                        <a class="btn btn-primary" href="{% url 'website:add_item' product.id %}">Order</a>
                    </div>

                {% endif %}
            </div>
        </div>

    </div>


    <a href="{% url 'website:products_list' %}">Return to Products Page</a>



</div>

{% endblock %}

e_store/templates/products_list.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} User | {{ user.username }} {% endblock %}


{% block body %}

<h1>User | {{ user.username }}</h1>
<hr>

<div class="container">



    <h2>All Products</h2>

    <div class="row text-center mx-auto">
        {% for product in products %}
        {% if product.stock > 0 %}
        <div class="text-center col-md-4 mx-auto">
            <a href="{% url 'website:product_detail' product.id %}">
                <div class="product card shadow" style="width: 10rem;">
                    <div>
                        <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.image }}">
                    </div>
                    <h4>{{ product.name }}</h4>
                    PRICE: {{ product.price }}<br>
                    

                </div>
            </a>

        </div>
        {% endif %}
        {% endfor %}
        
    </div>
</div>

{% endblock %}

e_store/templates/register.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Register {% endblock %}


{% block body %}

<div class="register-form">

    <form action="" method="POST">
        <div class="heading">
            <h2>Register</h2>
        </div>
        {% for message in messages %}
        <div class="messages">
            <h4 style="color: red; font-size: 1.5rem;">{{ message }}</h4>
        </div>
        {% endfor %}
        {% csrf_token %}

        {{ form.as_p }}
        
        <br>
        <div class="d-grid">
            <button class="btn btn-primary" type="submit">SignUp</button>
        </div>
    </form>

</div>

{% endblock %}

e_store/templates/update.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Edit {% endblock %}


{% block body %}

<div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary" type="submit">Proceed</button>

    </form>
</div>

{% endblock %}